### ISSUE TITLE
css 画一个三角形

### ISSUE THREAD

**Issue by zxf4399** [zxf4399/interview#6]
```css
// 正三角形
.triangle {
    width: 0;
    height: 0;
    border-style: solid;
    border-width: 0 23px 40px 23px;
    border-color: transparent transparent red transparent; 
}

// 倒三角形
.triangle {
    width: 0;
    height: 0;
    border-style: solid;
    border-width: 40px 23px 0 23px;
    border-color: red transparent transparent transparent; 
}
```
